import {useState,type ComponentType} from 'react';
import {NavLink,Outlet,Link,useLocation} from 'react-router-dom';
import {ChartNoAxesCombined,AudioLines,Map,CalendarDays,Users,Settings,LogOut,ArrowLeftRight,KeyRound,Home} from 'lucide-react';
import {useAuth,useFarm} from '../features/auth/Auth';
import {Button,Dropdown,ErrorBox} from './ui';
export function Shell(){const farm=useFarm();const auth=useAuth();const [error,setError]=useState<unknown>();const location=useLocation();const base=`/admin/${farm.farmId}`;
 const groups:{title:string;items:readonly (readonly [string,string,ComponentType<{size?:number}>])[]}[]=[{title:'Overview',items:[['Dashboard','dashboard',ChartNoAxesCombined],['Activity Logs','logs',AudioLines],['Map','map',Map]]},{title:'Team management',items:[['Employees','employees',Users],['Schedule','schedule',CalendarDays]]},{title:'Other',items:[['Settings','settings',Settings]]}];
 return <><aside className="sidebar"><Link to={`${base}/welcome`} className="farm-brand"><span className="avatar">{farm.data.farm.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span><div><strong>{farm.data.farm.name}</strong><small>Admin</small></div></Link><nav aria-label="Main navigation">{groups.map(g=><section key={g.title}><h2>{g.title}</h2>{g.items.map(([label,route,Icon])=><NavLink className={({isActive})=>`nav-item ${isActive?'active':''}`} key={route} to={`${base}/${route}`}><Icon size={16}/>{label}</NavLink>)}</section>)}</nav><div className="sidebar-bottom"><Dropdown className="account-dropdown" label={<><ArrowLeftRight size={16}/>Account</>}><Link to="/select-farm" className="nav-item"><Home size={16}/>Switch farm</Link><Link to="/change-password" className="nav-item"><KeyRound size={16}/>Change password</Link><Link to={`/worker/${farm.farmId}`} className="nav-item"><AudioLines size={16}/>Record my report</Link></Dropdown><Button onClick={()=>{auth.logout().catch(setError);}}><LogOut size={16}/>Log Out</Button></div></aside><main className="admin-main">{!!error&&<ErrorBox error={error}/>}<div className="route-enter" key={location.pathname}><Outlet/></div></main></>;
}
