import {createContext,useContext,useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {Link,Navigate,Outlet,useNavigate,useParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api,ApiError,setCsrf} from '../../api/client';
import type {AuthResult,Bootstrap,Membership} from '../../api/types';
import {Busy,Button,ErrorBox} from '../../components/ui';
import {clearUserDrafts,listUserDrafts} from '../worker/drafts';
interface AuthContextValue{session:AuthResult|null;loading:boolean;error:unknown;login:(username:string,password:string)=>Promise<void>;logout:()=>Promise<boolean>;reload:()=>Promise<void>;accept:(value:AuthResult)=>void;}
const AuthContext=createContext<AuthContextValue|null>(null);
export function useAuth(){const context=useContext(AuthContext);if(!context)throw new Error('Authentication context missing.');return context;}
export function AuthProvider({children}:{children:ReactNode}){
 const [session,setSession]=useState<AuthResult|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>();const cache=useQueryClient();
 const accept=(value:AuthResult)=>{setCsrf(value.csrf_token);setSession(value);setError(undefined);};
 const reload=async()=>{setLoading(true);try{accept(await api<AuthResult>('/me'));}catch(e){if(e instanceof ApiError&&e.status===401){setCsrf('');setSession(null);setError(undefined);}else setError(e);}finally{setLoading(false);}};
 useEffect(()=>{let live=true;const controller=new AbortController();api<AuthResult>('/me',{signal:controller.signal}).then(value=>{if(live)accept(value);}).catch(e=>{if(live&&!(e instanceof ApiError&&e.status===401))setError(e);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;controller.abort();};},[]);
 const login=async(username:string,password:string)=>{const result=await api<AuthResult>('/auth/login',{method:'POST',body:{username,password}});cache.clear();accept(result);};
 const logout=async()=>{if(session){let count:number|null=null;try{count=(await listUserDrafts(session.user.id)).length;}catch{count=null;}if((count===null||count>0)&&!window.confirm(count===null?'Local storage could not be inspected. Logging out may leave unsent audio in site storage. Continue and clear this site’s storage before sharing this device?':`You have ${count} unsent recording(s). Logging out will erase these local drafts. Continue?`))return false;await api('/auth/logout',{method:'POST'});try{await clearUserDrafts(session.user.id);}catch{window.alert('You are logged out. Local storage could not be cleared. Clear this site’s stored data before sharing this device.');}}setCsrf('');setSession(null);cache.clear();sessionStorage.removeItem('toph.farm');return true;};
 return <AuthContext.Provider value={{session,loading,error,login,logout,reload,accept}}>{children}</AuthContext.Provider>;
}
function destination(m:Membership){return m.role==='admin'?`/admin/${m.farm.id}/welcome`:`/worker/${m.farm.id}`;}
export function Entry(){const auth=useAuth();if(auth.loading)return <Busy/>;if(auth.error)return <main className="auth-page"><h1>TOPH</h1><ErrorBox error={auth.error} retry={()=>{void auth.reload();}}/></main>;if(!auth.session)return <Navigate to="/login" replace/>;if(auth.session.must_change_password)return <Navigate to="/change-password" replace/>;const selected=auth.session.memberships.find(m=>m.farm.id===sessionStorage.getItem('toph.farm'));const only=auth.session.memberships.length===1?auth.session.memberships[0]:selected;return <Navigate to={only?destination(only):'/select-farm'} replace/>;}
export function Login(){const auth=useAuth();const navigate=useNavigate();const [name,setName]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();if(auth.loading)return <Busy/>;if(auth.session)return <Navigate to="/" replace/>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError(undefined);try{await auth.login(name,password);navigate('/',{replace:true});}catch(err){setError(err);}finally{setBusy(false);}};
 return <main className="auth-page"><div className="wordmark">TOPH</div><div className="auth-orbit"/><h1>Welcome back</h1><p className="muted">Log in to your farm.</p><form className="stack" onSubmit={e=>{void submit(e);}}><label className="form-field">Username<input autoComplete="username" autoCapitalize="none" autoCorrect="off" value={name} onChange={e=>setName(e.target.value)} required maxLength={40}/></label><label className="form-field">Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required maxLength={128}/></label><Button type="submit" className="primary" disabled={busy}>{busy?'Logging in...':'Log in'}</Button></form>{!!error&&<ErrorBox error={error}/>}<p className="muted small" style={{marginTop:20}}>Ask your farm administrator for your username and temporary password.</p></main>;
}
export function ChangePassword(){const auth=useAuth();const navigate=useNavigate();const [current,setCurrent]=useState(''),[next,setNext]=useState(''),[repeat,setRepeat]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();const cache=useQueryClient();
 if(auth.loading)return <Busy/>;if(!auth.session)return <Navigate to="/login" replace/>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setError(undefined);if(next!==repeat){setError(new Error('The new passwords do not match.'));return;}setBusy(true);try{const result=await api<AuthResult>('/auth/change-password',{method:'POST',body:{current_password:current,new_password:next}});cache.clear();auth.accept(result);navigate('/',{replace:true});}catch(err){setError(err);}finally{setBusy(false);}};
 return <main className="auth-page"><div className="wordmark">TOPH</div><h1>Change your password</h1><p className="muted">Use 12-128 characters. Password-manager paste is welcome.</p><form className="stack" onSubmit={e=>{void submit(e);}}><label className="form-field">Current or temporary password<input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label className="form-field">New password<input required minLength={12} maxLength={128} type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)}/></label><label className="form-field">Repeat new password<input required type="password" autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></label><Button type="submit" className="primary" disabled={busy}>Save password</Button></form>{!!error&&<ErrorBox error={error}/>}<Button onClick={()=>{auth.logout().catch(setError);}}>Log out</Button></main>;
}
export function FarmPicker(){const auth=useAuth();const navigate=useNavigate();const [error,setError]=useState<unknown>();if(auth.loading)return <Busy/>;if(!auth.session)return <Navigate to="/login" replace/>;if(auth.session.must_change_password)return <Navigate to="/change-password" replace/>;return <main className="auth-page"><div className="wordmark">TOPH</div><h1>Choose your farm</h1><p className="muted">Signed in as {auth.session.user.name}.</p><div className="stack">{auth.session.memberships.map(m=><button className="farm-choice" key={m.id} onClick={()=>{sessionStorage.setItem('toph.farm',m.farm.id);navigate(destination(m));}}>{m.farm.name}<span>{m.role}</span></button>)}</div>{auth.session.memberships.length===0&&<p>No enabled farm memberships. Contact your administrator.</p>}<Button onClick={()=>{auth.logout().catch(setError);}}>Log out</Button>{!!error&&<ErrorBox error={error}/>}</main>;}
interface FarmContextValue{farmId:string;userId:string;role:'admin'|'worker';path:string;data:Bootstrap;}
const FarmContext=createContext<FarmContextValue|null>(null);
export function useFarm(){const context=useContext(FarmContext);if(!context)throw new Error('Farm context missing.');return context;}
export function FarmGate({mode,children}:{mode:'admin'|'worker';children?:ReactNode}){
 const auth=useAuth();const {farmId=''}=useParams();const userId=auth.session?.user.id||'';const membership=auth.session?.memberships.find(m=>m.farm.id===farmId);const path=`/farms/${farmId}`;
 const query=useQuery({queryKey:[userId,farmId,'bootstrap'],queryFn:({signal})=>api<Bootstrap>(`${path}/bootstrap`,{signal}),enabled:!!membership&&!auth.session?.must_change_password});
 if(auth.loading)return <Busy/>;if(!auth.session)return <Navigate to="/login" replace/>;if(auth.session.must_change_password)return <Navigate to="/change-password" replace/>;if(!membership)return <Navigate to="/select-farm" replace/>;if(mode==='admin'&&membership.role!=='admin')return <Navigate to={`/worker/${farmId}`} replace/>;
 if(query.isPending)return <Busy label="Opening your farm..."/>;if(query.error)return <main className="auth-page"><ErrorBox error={query.error} retry={()=>{void query.refetch();}}/><Link to="/select-farm">Choose another farm</Link></main>;
 return <FarmContext.Provider value={{farmId,userId,path,data:query.data,role:query.data.membership.role}}>{children||<Outlet/>}</FarmContext.Provider>;
}
