import {useState,type FormEvent} from 'react';
import {useInfiniteQuery,useQueryClient} from '@tanstack/react-query';
import {api,queryString} from '../../api/client';
import type {Page,Shift,ShiftInput} from '../../api/types';
import {useFarm} from '../auth/Auth';
import {Busy,Button,Empty,ErrorBox,Modal,timeLabel} from '../../components/ui';
import {dayBounds,localToday,toInstant,toLocalInput,type Disambiguation} from './time';
export default function SchedulePage(){const farm=useFarm(),cache=useQueryClient();const [day,setDay]=useState(()=>localToday(farm.data.farm.timezone)),[edit,setEdit]=useState<Shift|'new'|null>(null),[error,setError]=useState<unknown>();const bounds=dayBounds(day,farm.data.farm.timezone);
 const query=useInfiniteQuery({queryKey:[farm.userId,farm.farmId,'shifts',day],initialPageParam:null as string|null,queryFn:({pageParam,signal})=>api<Page<Shift>>(`${farm.path}/shifts${queryString({...bounds,cursor:pageParam,limit:100})}`,{signal}),getNextPageParam:p=>p.next_cursor||undefined});
 const refresh=()=>cache.invalidateQueries({queryKey:[farm.userId,farm.farmId]});
 const remove=async(shift:Shift)=>{if(!window.confirm('Delete this planned assignment? A linked report will prevent deletion.'))return;try{await api(`${farm.path}/shifts/${shift.id}`,{method:'DELETE'});await refresh();}catch(e){setError(e);}};
 const rows=query.data?.pages.flatMap(p=>p.items).sort((a,b)=>a.start_at.localeCompare(b.start_at))||[];
 return <><header className="page-heading"><div><h1>Schedule</h1><p>Planned assignments in {farm.data.farm.timezone}</p></div><Button className="primary" onClick={()=>setEdit('new')}>Add assignment</Button></header><label className="form-field" style={{maxWidth:240,marginBottom:20}}>Display date<input type="date" required value={day} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label><p className="small muted">A planned shift does not confirm attendance or actual work.</p>{!!error&&<ErrorBox error={error}/>}<section className="panel">{query.isPending?<Busy/>:query.error?<ErrorBox error={query.error} retry={()=>{void query.refetch();}}/>:rows.length?<div className="table-scroll"><table className="management-table"><thead><tr><th>Employee</th><th>Scheduled time</th><th>Field</th><th>Activity</th><th>Fertilizer</th><th>Actions</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.employee.name}</td><td>{timeLabel(s.start_at,farm.data.farm.timezone)} - {timeLabel(s.end_at,farm.data.farm.timezone)}</td><td>{s.field?.name||'Unassigned'}</td><td>{s.activity?.name||'Unassigned'}</td><td>{s.fertilizer?.name||'None'}</td><td><div className="inline-actions"><Button onClick={()=>setEdit(s)}>Edit</Button><Button onClick={()=>{void remove(s);}}>Delete</Button></div></td></tr>)}</tbody></table></div>:<Empty title="No planned assignments for this date"/>}</section>{query.hasNextPage&&<Button className="load-more" onClick={()=>{void query.fetchNextPage();}}>Load more</Button>}{edit&&<ShiftForm existing={edit==='new'?null:edit} day={day} close={()=>setEdit(null)} saved={()=>{setEdit(null);void refresh();}}/>}</>;
}
function ShiftForm({existing,day,close,saved}:{existing:Shift|null;day:string;close:()=>void;saved:()=>void}){const farm=useFarm();const zone=farm.data.farm.timezone;const [employee,setEmployee]=useState(existing?.employee.id||''),[start,setStart]=useState(existing?toLocalInput(existing.start_at,zone):`${day}T08:00`),[end,setEnd]=useState(existing?toLocalInput(existing.end_at,zone):`${day}T16:00`),[field,setField]=useState(existing?.field?.id||''),[activity,setActivity]=useState(existing?.activity?.id||''),[fertilizer,setFertilizer]=useState(existing?.fertilizer?.id||''),[choice,setChoice]=useState<Disambiguation>('reject'),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError(undefined);try{const data:ShiftInput={employee_id:employee,start_at:toInstant(start,zone,choice),end_at:toInstant(end,zone,choice),field_id:field||null,activity_id:activity||null,fertilizer_id:fertilizer||null};if(Date.parse(data.end_at)<=Date.parse(data.start_at))throw new Error('End time must follow start time.');await api(`${farm.path}/shifts${existing?'/'+existing.id:''}`,{method:existing?'PATCH':'POST',body:data});saved();}catch(err){setError(err);}finally{setBusy(false);}};
 return <Modal title={existing?'Edit planned assignment':'New planned assignment'} close={close}><form className="stack" onSubmit={e=>{void submit(e);}}><label className="form-field">Worker<select value={employee} required onChange={e=>setEmployee(e.target.value)}><option value="">Choose a worker</option>{farm.data.workers.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><div className="form-grid"><label className="form-field">Start ({zone})<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="form-field">End ({zone})<input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label className="form-field">Daylight-saving repeated time<select value={choice} onChange={e=>setChoice(e.target.value as Disambiguation)}><option value="reject">Ask when ambiguous</option><option value="earlier">First occurrence</option><option value="later">Second occurrence</option></select></label><label className="form-field">Field<select value={field} onChange={e=>setField(e.target.value)}><option value="">Unassigned</option>{farm.data.fields.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label className="form-field">Activity<select value={activity} onChange={e=>setActivity(e.target.value)}><option value="">Unassigned</option>{farm.data.activities.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label className="form-field">Fertilizer<select value={fertilizer} onChange={e=>setFertilizer(e.target.value)}><option value="">None</option>{farm.data.fertilizers.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><Button className="primary" type="submit" disabled={busy}>Save assignment</Button>{!!error&&<ErrorBox error={error}/>}</form></Modal>;
}
