import type {Turn} from '../../api/types';
export interface Draft {id:string;user_id:string;farm_id:string;blob:Blob;content_type:string;duration_ms:number;recorded_at:string;transcript:Turn[];waveform_peaks:number[];interview_version:string;shift_id:string|null;recording_id?:string;transcription_incomplete?:boolean;}
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(!globalThis.indexedDB){reject(new Error('Local recording storage is unavailable. Enable site storage before recording.'));return;}const request=indexedDB.open('toph-private-drafts',1);request.onupgradeneeded=()=>{request.result.createObjectStore('drafts',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('Could not open local recording storage. Check browser storage settings.'));});}
async function operation<T>(mode:IDBTransactionMode,run:(store:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',mode);const request=run(tx.objectStore('drafts'));let result:T;request.onsuccess=()=>{result=request.result;};tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(new Error('Could not save the local recording. Keep this page open and free some device storage.'));};tx.onabort=()=>{db.close();reject(new Error('Local recording storage was interrupted.'));};});}
export async function saveDraft(draft:Draft){await operation('readwrite',store=>store.put(draft));}
export async function listUserDrafts(userId:string){const all=await operation<Draft[]>('readonly',store=>store.getAll());return all.filter(d=>d.user_id===userId).sort((a,b)=>b.recorded_at.localeCompare(a.recorded_at));}
export async function listDrafts(userId:string,farmId:string){return (await listUserDrafts(userId)).filter(d=>d.farm_id===farmId);}
export async function deleteDraft(id:string){await operation('readwrite',store=>store.delete(id));}
export async function clearUserDrafts(userId:string){for(const draft of await listUserDrafts(userId))await deleteDraft(draft.id);}
