import {useEffect,useState,type ReactNode} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,ArrowRight,Check,Mic,Volume2} from 'lucide-react';
import {useAuth,useFarm} from '../auth/Auth';
import {Busy,Button,Empty,ErrorBox,dateLabel,timeLabel} from '../../components/ui';
import {LogCards} from '../logs/LogCards';
import {LogDialog} from '../logs/LogDetailView';
import {useLogs} from '../logs/queries';
import {QUESTIONS,useVoiceInterview} from './useVoiceInterview';
import {type Draft,listDrafts,saveDraft,deleteDraft} from './drafts';
import {type SaveStage,submitDraft} from './submission';
function WorkerFooter(){const auth=useAuth();const farm=useFarm();const [error,setError]=useState<unknown>();return <><footer className="worker-footer"><Link to={`/worker/${farm.farmId}`}>Home</Link><Link to={`/worker/${farm.farmId}/history`}>My reports</Link>{farm.role==='admin'&&<Link to={`/admin/${farm.farmId}/dashboard`}>Admin dashboard</Link>}<Link to="/select-farm">Switch farm</Link><Link to="/change-password">Password</Link><button onClick={()=>{auth.logout().catch(setError);}}>Log out</button></footer>{!!error&&<ErrorBox error={error}/>}</>;}
export function WorkerHome({history=false}:{history?:boolean}){
 const farm=useFarm();const [selected,setSelected]=useState<string|null>(null);const reports=useLogs({employee_id:farm.userId,direction:'desc'},history?20:6);const [drafts,setDrafts]=useState<Draft[]>([]);
 useEffect(()=>{listDrafts(farm.userId,farm.farmId).then(setDrafts).catch(()=>undefined);},[farm.userId,farm.farmId]);
 const logs=reports.data?.pages.flatMap(p=>p.items)||[];
 return <main className="worker-home"><header className="worker-heading"><Link to={`/worker/${farm.farmId}`} className="wordmark">TOPH</Link><span className="muted small">{farm.data.farm.name}</span></header><h1>{history?'My reports':`Hello, ${farm.data.user.name.split(' ')[0]}`}</h1><p className="muted">{history?'Your submitted activity and fertilizer reports.':'Talk through your work. Keep your farm informed.'}</p><Link className="button primary record-link" to={`/worker/${farm.farmId}/record`}><Mic size={18}/>Record your work<ArrowRight size={17}/></Link>{drafts.length>0&&<p><Link className="text-link" to={`/worker/${farm.farmId}/record`}>{drafts.length} unsent recording(s) on this device. Continue or retry.</Link></p>}
 {!history&&<section className="worker-schedule"><h2>Today’s planned schedule</h2><p className="small muted">Times shown in {farm.data.farm.timezone}. A schedule does not confirm attendance.</p>{farm.data.shifts.length?farm.data.shifts.map(s=><div className="worker-shift" key={s.id}><strong>{s.activity?.name||'Activity not assigned'} · {s.fertilizer?.name||'No fertilizer assigned'}</strong><span>{s.field?.name||'Field not assigned'} · {timeLabel(s.start_at,farm.data.farm.timezone)} - {timeLabel(s.end_at,farm.data.farm.timezone)}</span></div>):<p className="muted">No planned shifts for today.</p>}</section>}
 <h2>{history?'All my reports':'Recent reports'}</h2>{reports.isPending?<Busy label="Loading reports..."/>:reports.error?<ErrorBox error={reports.error} retry={()=>{void reports.refetch();}}/>:logs.length?<LogCards items={logs} open={setSelected}/>:<Empty title="No reports yet">Your completed reports will appear here.</Empty>}
 {history&&reports.hasNextPage&&<Button disabled={reports.isFetchingNextPage} onClick={()=>{void reports.fetchNextPage();}}>Load more</Button>}{selected&&<LogDialog id={selected} close={()=>setSelected(null)}/>}<WorkerFooter/></main>;
}
function DraftReview({draft,onChange,onSubmit,onRemove,busy}:{draft:Draft;onChange:(draft:Draft)=>void;onSubmit:()=>void;onRemove:()=>void;busy:boolean}){
 const [url,setUrl]=useState(''),[supplement,setSupplement]=useState(''),[error,setError]=useState<unknown>();
 useEffect(()=>{const value=URL.createObjectURL(draft.blob);setUrl(value);return()=>URL.revokeObjectURL(value);},[draft.blob]);
 const commit=async()=>{setError(undefined);const transcript=[...draft.transcript];if(supplement.trim())transcript.push({speaker:'worker',text:'[Worker-entered transcript correction] '+supplement.trim(),offset_ms:draft.duration_ms});if(!transcript.some(t=>t.speaker==='worker'&&t.text.trim())){setError(new Error('Enter an honest transcript of your work before continuing.'));return;}const next={...draft,transcript,transcription_incomplete:false};try{await saveDraft(next);onChange(next);setSupplement('');}catch(e){setError(e);}};
 return <section className="draft-review"><h2>Review recording</h2><p className="muted small">Audio and transcript are self-reported. Listen and check before saving.</p><audio controls src={url} preload="metadata" className="full-width"/>{url&&<a className="button" href={url} download={`toph-recording-${draft.id}.${draft.content_type==='audio/mp4'?'m4a':draft.content_type==='audio/ogg'?'ogg':'webm'}`}>Save audio backup</a>}<div className="draft-transcript">{draft.transcript.length?draft.transcript.map((t,i)=><p key={i}><strong>{t.speaker==='worker'?'You':'Assistant'}: </strong>{t.text}</p>):<p>No transcript was received. Your audio is retained.</p>}</div>
 {draft.transcription_incomplete&&<p role="alert">Speech transcription was incomplete. Listen to the audio, add any missing worker answers, then confirm the transcript below.</p>}
 {!draft.recording_id&&<><label className="form-field small">Optional transcript correction, entered by you<textarea value={supplement} disabled={busy} maxLength={12000} onChange={e=>setSupplement(e.target.value)} placeholder="Add only what you actually said or did." rows={4}/></label><Button disabled={busy} onClick={()=>{void commit();}}>Confirm transcript{supplement.trim()?' and add correction':''}</Button></>}
 {!!error&&<ErrorBox error={error}/>}<Button className="primary full-width" disabled={busy||!!draft.transcription_incomplete||!draft.transcript.some(t=>t.speaker==='worker')} onClick={onSubmit}>{busy?'Saving...':draft.recording_id?'Retry saving report':'Save report'}</Button><Button disabled={busy} onClick={onRemove}>Discard local draft</Button><p className="small muted">Your draft stays on this device until a report is saved. Keep this page open during upload.</p></section>;
}
export function WorkerRecord(){
 const farm=useFarm();const navigate=useNavigate();const cache=useQueryClient();const voice=useVoiceInterview({userId:farm.userId,farmId:farm.farmId,path:farm.path});
 const [shift,setShift]=useState<string>(()=>{const matches=farm.data.shifts.filter(s=>Date.parse(s.start_at)<=Date.now()&&Date.parse(s.end_at)>Date.now());return matches.length===1?matches[0].id:'';});
 const [drafts,setDrafts]=useState<Draft[]>([]),[selected,setSelected]=useState<Draft|null>(null),[stage,setStage]=useState<SaveStage|null>(null),[error,setError]=useState<unknown>(),[success,setSuccess]=useState<string|null>(null);
 const reload=()=>listDrafts(farm.userId,farm.farmId).then(setDrafts).catch(setError);
 useEffect(()=>{void reload();},[farm.userId,farm.farmId]);
 useEffect(()=>{if(voice.draft){setSelected(voice.draft);void reload();}},[voice.draft]);
 const saving=stage!==null&&stage!=='completed';
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(saving){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[saving]);
 const submit=async()=>{if(!selected||saving)return;setError(undefined);try{const report=await submitDraft(farm.path,selected,setStage,message=>setError(new Error(message)));setSuccess(report.id);setSelected(null);await reload();void cache.invalidateQueries({queryKey:[farm.userId,farm.farmId]});}catch(e){setError(e);setStage(null);}};
 const discard=async()=>{if(!selected||!window.confirm('Delete this local draft? Confirmed audio already saved on the server will remain.'))return;try{await deleteDraft(selected.id);setSelected(null);await reload();}catch(e){setError(e);}};
 const back=()=>{if(voice.active||saving){setError(new Error('Finish this recording or wait for saving before leaving.'));return;}navigate(`/worker/${farm.farmId}`);};
 let body:ReactNode;
 if(success){body=<div className="voice-success"><Check size={48}/><h2>Report saved</h2><p className="muted">Your farm administrator can now read your report.</p><Link className="button primary" to={`/worker/${farm.farmId}/history`}>View my reports</Link><Button onClick={()=>{setSuccess(null);setStage(null);setError(undefined);}}>Record another</Button></div>;}
 else if(selected&&!voice.active){body=<><DraftReview draft={selected} onChange={setSelected} onSubmit={()=>{void submit();}} onRemove={()=>{void discard();}} busy={saving}/>{saving&&<Busy label={stage==='generating'?'Audio saved. Creating your report...':stage==='uploading'?'Uploading audio directly to private storage...':'Saving recording details...'}/>}</>;}
 else if(voice.active){body=<><span className="voice-counter">{voice.ui.step+1}/5</span><div className="voice-question" key={`${voice.ui.step}-${voice.ui.phase}`}>
 {voice.ui.phase==='confirmed'?<h2 className="confirmed-answer">Got it<br/>{voice.ui.answer}</h2>:<><h2>{voice.ui.phase==='done'?'All done':QUESTIONS[voice.ui.step]}</h2>{voice.ui.phase==='confirming'&&voice.ui.answer&&<p className="confirmed-label">{voice.ui.answer}</p>}<p className="small muted" aria-live="off">{voice.speaker==='worker'?'You':'TOPH assistant'}</p><p className="live-transcript" aria-live="polite" aria-atomic="false">{voice.liveText||'Listening...'}</p></>}
 {voice.ui.phase==='confirming'&&<div className="confirmation-actions"><Button onClick={()=>voice.sendText('Yes, that is correct.')} disabled={voice.phase==='finishing'}>Yes, correct</Button><Button onClick={()=>voice.sendText('No, please let me correct my answer.')} disabled={voice.phase==='finishing'}>Let me correct that</Button></div>}
 </div><div className="voice-actions"><Button onClick={()=>{void voice.finish().catch(setError);}} disabled={voice.phase==='finishing'||voice.phase==='connecting'}>{voice.phase==='finishing'?'Preserving recording...':'Finish and review'}</Button><Button onClick={voice.resumeAudio}><Volume2 size={14}/>Resume assistant audio</Button><p className="small muted">Stay on this page. You can interrupt the assistant and correct your answers.</p></div></>;}
 else{body=<><h2>Tell us about your work</h2><p className="live-transcript">Tap the circle to begin. TOPH will ask about your activity, fertilizer, field, work details, and any issues.</p><label className="form-field shift-select">Link a planned shift, optional<select value={shift} onChange={e=>setShift(e.target.value)}><option value="">No linked shift</option>{farm.data.shifts.map(s=><option key={s.id} value={s.id}>{s.activity?.name||'Planned work'} · {s.fertilizer?.name||'No fertilizer assigned'} · {s.field?.name||'No field'} · {timeLabel(s.start_at,farm.data.farm.timezone)}</option>)}</select></label><Button className="primary full-width" onClick={()=>{setError(undefined);void voice.start(shift||null);}}>Start voice report</Button></>;}
 return <main className="voice-page"><header className="voice-top"><button aria-label="Back to worker home" className="voice-back" onClick={back}><ArrowLeft size={18}/></button><h1 className="wordmark">TOPH</h1><button className={`voice-ring ${!voice.active&&!selected&&!success?'pulse':''}`} aria-label={voice.active?'Recording in progress':'Start voice report'} disabled={voice.active||!!selected||!!success||saving} style={voice.active?{transform:`scale(${1+voice.amplitude*.1})`,borderWidth:30+voice.amplitude*5}:undefined} onClick={()=>{setError(undefined);void voice.start(shift||null);}}/>
 <div className="voice-status">{voice.active&&<span className="recording-dot"/>}{voice.phase==='connecting'?'Connecting...':voice.phase==='finishing'?'Finishing...':voice.active?`${voice.phase==='speaking'?'TOPH speaking':'Listening'} · ${Math.floor(voice.elapsed/60)}:${String(voice.elapsed%60).padStart(2,'0')}`:selected?'Recording ready to review':success?'Saved':'Tap to start'}</div><p className="recording-disclosure">TOPH is an AI assistant. This conversation is recorded and saved for your farm.</p></header>
 <div className="voice-bottom">{body}{!!(error||voice.error)&&<ErrorBox error={error||voice.error}/>} {!voice.active&&!saving&&drafts.length>0&&<section className="saved-drafts"><h3>Unsent recordings on this device</h3>{drafts.map(d=><div key={d.id}><span>{dateLabel(d.recorded_at,farm.data.farm.timezone)} · {Math.ceil(d.duration_ms/1000)} seconds</span><Button onClick={()=>{setSelected(d);setSuccess(null);setStage(null);setError(undefined);}}>Review</Button></div>)}</section>}</div></main>;
}
