import {useState,type FormEvent} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {api} from '../../api/client';
import type {FieldDetail,Named} from '../../api/types';
import {useFarm} from '../auth/Auth';
import {Button,ErrorBox,Modal} from '../../components/ui';
export default function SettingsPage(){const farm=useFarm();return <><header className="page-heading"><div><h1>Settings</h1><p>Farm details, field boundaries, and reporting vocabulary</p></div></header><div className="settings-grid"><FarmSettings/><FieldsSettings/><Catalog title="Activities" kind="activities" items={farm.data.activities}/><Catalog title="Fertilizers" kind="fertilizers" items={farm.data.fertilizers}/><Catalog title="Tags" kind="tags" items={farm.data.tags}/></div></>;}
function useRefresh(){const farm=useFarm();const cache=useQueryClient();return ()=>cache.invalidateQueries({queryKey:[farm.userId,farm.farmId]});}
function FarmSettings(){const farm=useFarm(),refresh=useRefresh();const [name,setName]=useState(farm.data.farm.name),[zone,setZone]=useState(farm.data.farm.timezone),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError(undefined);setSaved(false);try{await api(farm.path,{method:'PATCH',body:{name,timezone:zone}});await refresh();setSaved(true);}catch(err){setError(err);}finally{setBusy(false);}};return <section className="settings-panel"><h2>Farm details</h2><form className="stack" onSubmit={e=>{void submit(e);}}><label className="form-field">Farm name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="form-field">IANA timezone<input required placeholder="America/Los_Angeles" value={zone} onChange={e=>setZone(e.target.value)}/></label><Button type="submit" disabled={busy}>Save farm</Button>{saved&&<span className="success-message" role="status">Farm saved.</span>}{!!error&&<ErrorBox error={error}/>}</form></section>;}
function Catalog({title,kind,items}:{title:string;kind:'activities'|'fertilizers'|'tags';items:Named[]}){const farm=useFarm(),refresh=useRefresh();const [name,setName]=useState(''),[edit,setEdit]=useState<Named|null>(null),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError(undefined);try{await api(`${farm.path}/${kind}${edit?'/'+edit.id:''}`,{method:edit?'PATCH':'POST',body:{name}});setName('');setEdit(null);await refresh();}catch(err){setError(err);}finally{setBusy(false);}};const remove=async(item:Named)=>{if(!window.confirm(`Delete ${item.name}? Referenced items cannot be deleted.`))return;setBusy(true);try{await api(`${farm.path}/${kind}/${item.id}`,{method:'DELETE'});await refresh();}catch(err){setError(err);}finally{setBusy(false);}};return <section className="settings-panel"><h2>{title}</h2><form onSubmit={e=>{void submit(e);}} className="stack"><label className="form-field">{edit?'Rename':'Add'} {kind==='activities'?'activity':kind==='fertilizers'?'fertilizer':'tag'}<input required maxLength={kind==='tags'?80:100} value={name} onChange={e=>setName(e.target.value)}/></label><div className="inline-actions"><Button type="submit" disabled={busy}>{edit?'Save name':'Add'}</Button>{edit&&<Button onClick={()=>{setEdit(null);setName('');}}>Cancel</Button>}</div></form>{!!error&&<ErrorBox error={error}/>}<div className="catalog-list">{items.map(item=><div className="catalog-row" key={item.id}><span>{item.name}</span>{kind!=='tags'&&<div className="inline-actions"><Button onClick={()=>{setEdit(item);setName(item.name);}}>Rename</Button><Button disabled={busy} onClick={()=>{void remove(item);}}>Delete</Button></div>}</div>)}</div>{items.length===0&&<p className="muted small">No {kind} yet.</p>}</section>;}
function FieldsSettings(){const farm=useFarm(),refresh=useRefresh();const [opened,setOpened]=useState<FieldDetail|'new'|null>(null),[error,setError]=useState<unknown>();const edit=async(id:string)=>{try{setOpened(await api<FieldDetail>(`${farm.path}/fields/${id}`));}catch(e){setError(e);}};const remove=async(field:Named)=>{if(!window.confirm(`Delete ${field.name}? Existing reports or schedules may prevent deletion.`))return;try{await api(`${farm.path}/fields/${field.id}`,{method:'DELETE'});await refresh();}catch(e){setError(e);}};return <section className="settings-panel"><h2>Fields</h2><p className="muted small">Add actual boundaries as GeoJSON Polygon or MultiPolygon geometry. Use longitude, then latitude. Maximum 1,000 positions.</p><Button onClick={()=>setOpened('new')}>Add field</Button>{!!error&&<ErrorBox error={error}/>}<div className="catalog-list">{farm.data.fields.map(f=><div className="catalog-row" key={f.id}><span>{f.name}</span><div className="inline-actions"><Button onClick={()=>{void edit(f.id);}}>Edit</Button><Button onClick={()=>{void remove(f);}}>Delete</Button></div></div>)}</div>{opened&&<FieldForm existing={opened==='new'?null:opened} close={()=>setOpened(null)} saved={()=>{setOpened(null);void refresh();}}/>}</section>;}
function FieldForm({existing,close,saved}:{existing:FieldDetail|null;close:()=>void;saved:()=>void}){const farm=useFarm();const [name,setName]=useState(existing?.name||''),[geometry,setGeometry]=useState(existing?JSON.stringify(existing.geometry,null,2):''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const shape:unknown=JSON.parse(geometry);await api(`${farm.path}/fields${existing?'/'+existing.id:''}`,{method:existing?'PATCH':'POST',body:{name,geometry:shape}});saved();}catch(err){setError(err);}finally{setBusy(false);}};return <Modal title={existing?'Edit field':'Add field'} close={close}><form className="stack" onSubmit={e=>{void submit(e);}}><label className="form-field">Field name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="form-field">GeoJSON geometry<textarea required rows={12} value={geometry} onChange={e=>setGeometry(e.target.value)} placeholder='{"type":"Polygon","coordinates":[...]}'/></label><p className="small muted">Paste the geometry object, not a FeatureCollection. Every ring must close with its starting position.</p><Button type="submit" className="primary" disabled={busy}>Save boundary</Button>{!!error&&<ErrorBox error={error}/>}</form></Modal>;}
