import {useState,type FormEvent} from 'react';
import {useInfiniteQuery,useQueryClient} from '@tanstack/react-query';
import {Plus} from 'lucide-react';
import {api,queryString} from '../../api/client';
import type {Member,MemberCreated,Page} from '../../api/types';
import {useFarm} from '../auth/Auth';
import {Busy,Button,Empty,ErrorBox,Modal} from '../../components/ui';
export default function EmployeesPage(){
 const farm=useFarm(),cache=useQueryClient();const [add,setAdd]=useState(false),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(''),[credentials,setCredentials]=useState<{username:string;password:string}|null>(null);
 const query=useInfiniteQuery({queryKey:[farm.userId,farm.farmId,'members'],initialPageParam:null as string|null,queryFn:({pageParam,signal})=>api<Page<Member>>(`${farm.path}/members${queryString({limit:100,cursor:pageParam})}`,{signal}),getNextPageParam:last=>last.next_cursor||undefined});
 const refresh=()=>cache.invalidateQueries({queryKey:[farm.userId,farm.farmId]});
 const change=async(member:Member,values:object)=>{setBusy(member.id);setError(undefined);try{await api(`${farm.path}/members/${member.id}`,{method:'PATCH',body:values});await refresh();}catch(e){setError(e);}finally{setBusy('');}};
 const reset=async(member:Member)=>{if(!window.confirm(`Reset ${member.name}'s password and revoke their sessions?`))return;setBusy(member.id);try{const result=await api<{temporary_password:string}>(`${farm.path}/members/${member.id}/reset-password`,{method:'POST'});setCredentials({username:member.username,password:result.temporary_password});}catch(e){setError(e);}finally{setBusy('');}};
 const rows=query.data?.pages.flatMap(p=>p.items)||[];
 return <><header className="page-heading"><div><h1>Employees</h1><p>Manage your farm's workers and administrators</p></div><Button className="primary" onClick={()=>setAdd(true)}><Plus size={16}/>Add employee</Button></header>{!!error&&<ErrorBox error={error}/>}<section className="panel">{query.isPending?<Busy/>:query.error?<ErrorBox error={query.error} retry={()=>{void query.refetch();}}/>:rows.length?<div className="table-scroll"><table className="management-table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Access</th><th>Account</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{m.name}{m.user_id===farm.userId&&<small> You</small>}</td><td>{m.username}</td><td><select aria-label={`Role for ${m.name}`} value={m.role} disabled={busy===m.id} onChange={e=>{void change(m,{role:e.target.value});}}><option value="worker">Worker</option><option value="admin">Admin</option></select></td><td><Button disabled={busy===m.id} onClick={()=>{if(window.confirm(`${m.is_enabled?'Disable':'Enable'} ${m.name}'s farm access?`))void change(m,{is_enabled:!m.is_enabled});}}>{m.is_enabled?'Enabled':'Disabled'}</Button></td><td>{m.role==='worker'?<Button disabled={busy===m.id} onClick={()=>{void reset(m);}}>Reset password</Button>:<span className="muted small">Operator reset only</span>}</td></tr>)}</tbody></table></div>:<Empty title="No employees"/>}</section>{query.hasNextPage&&<Button className="load-more" onClick={()=>{void query.fetchNextPage();}}>Load more</Button>}{add&&<AddMember close={()=>setAdd(false)} saved={m=>{setAdd(false);setCredentials({username:m.member.username,password:m.temporary_password});void refresh();}}/>}{credentials&&<Modal title="Give this password to the employee" close={()=>setCredentials(null)}><p>The password is shown once. They must change it after logging in.</p><dl className="credential"><dt>Username</dt><dd>{credentials.username}</dd><dt>Temporary password</dt><dd><code>{credentials.password}</code></dd></dl><Button onClick={()=>{navigator.clipboard.writeText(`Username: ${credentials.username}\nTemporary password: ${credentials.password}`).catch(setError);}}>Copy credentials</Button></Modal>}</>;
}
function AddMember({close,saved}:{close:()=>void;saved:(value:MemberCreated)=>void}){const farm=useFarm();const [name,setName]=useState(''),[username,setUsername]=useState(''),[role,setRole]=useState('worker'),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{saved(await api<MemberCreated>(`${farm.path}/members`,{method:'POST',body:{name,username,role}}));}catch(err){setError(err);}finally{setBusy(false);}};return <Modal title="Create employee account" close={close}><form className="stack" onSubmit={e=>{void submit(e);}}><label className="form-field">Full name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="form-field">Username<input required minLength={3} maxLength={40} autoCapitalize="none" value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="form-field">Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="worker">Worker</option><option value="admin">Admin</option></select></label><Button type="submit" className="primary" disabled={busy}>Create account</Button>{!!error&&<ErrorBox error={error}/>}</form></Modal>;}
